services:
  installer:
    container_name: azuracast_installer
    image: 'giva9712/boostcast:v1'
    volumes:
      - './:/installer'
    restart: 'no'
    entrypoint: docker_installer
    command: install
    privileged: true
