#!/usr/bin/env bash

# exec tmpreaper 12h --verbose \
#     --protect '.tmpreaper' \
#     --protect 'proxies' \
#     --protect 'service_*.log' \
#     /tmp/app_nginx_client \
#     /tmp/app_fastcgi_temp \
#     /var/azuracast/stations/*/temp \
#     /var/azuracast/www_tmp
exec tmpreaper 12h --verbose \
    --protect '.tmpreaper' \
    --protect 'proxies' \
    --protect 'service_*.log' \
    --protect 'active_server' \
    /tmp/nginx_client \
    /tmp/nginx_fastcgi \
    /tmp/nginx_cache \
    /tmp/sftpgo_temp \
    /var/azuracast/stations/*/temp \
    /var/azuracast/www_tmp