#!/usr/bin/env bash

if [ `whoami` != 'azuracast' ]; then
    exec gosu azuracast uptime_wait "$@"
fi

cd /var/azuracast/www
exec php backend/bin/uptime_wait "$@"

# #!/bin/bash
# set -e

# gosu azuracast php /var/azuracast/www/bin/uptime_wait || exit 1

# exec "$@"
